### ISSUE TITLE
Fix form design in expanded event card

### ISSUE THREAD

**Issue by artfuldev** [artfuldev/devday#61]
![image](https://cloud.githubusercontent.com/assets/3091087/18136892/fd35983c-6fc3-11e6-86eb-39f66e65204b.png)

Things to fix: submit button style, height of form, height of card based on form, maybe also the margin/padding for location and attending sections

**Comment by sdn2525** [comment]
@artfuldev This issue is fixed. Please test, verify & close this issue.

**Comment by artfuldev** [comment]
This one is done.
