### ISSUE TITLE
Fix form design in event card

### ISSUE THREAD

**Issue by artfuldev** [artfuldev/devday#63]
![image](https://cloud.githubusercontent.com/assets/3091087/18136815/abd5ec9e-6fc3-11e6-9a2a-572ebe5e055e.png)

Things to fix off the top of my head: background, text color, button styles, close button

**Comment by sdn2525** [comment]
@artfuldev This issue is fixed. Please test, verify & close this issue.

**Comment by artfuldev** [comment]
This is done, thanks!
